backend:
  name: github
  repo: alberto56/antichar2
  base_url: https://suresh-issue-82.dcycleproject.org
  branch: master
  auth_endpoint: /auth/github/repo/694f515d18f56cc35826654b
media_folder: assets/uploads
collections:
  - name: blog posts
    create: true
    label: Blog
    folder: _posts/
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - label: Manifeste
        name: manifeste
        file: manifeste/index.md
        fields:
          - label: Title
            name: title
            widget: hidden
            default: About
          - label: permalink
            name: permalink
            widget: hidden
            default: /about/
          - label: Layout
            name: layout
            widget: hidden
            default: page
          - label: Body
            name: body
            widget: markdown
